export const MEMBERS = [
  {
    id: 0,
    gymId: "0000",
    firstName: "Khabib",
    lastName: "Nurmagomedov",
    rank: "purple",
  },
  {
    id: 1,
    gymId: "1111",
    firstName: "Conor",
    lastName: "McGregor",
    rank: "brown",
  },
  {
    id: 2,
    gymId: "2222",
    firstName: "Tony",
    lastName: "Ferguson",
    rank: "black",
  },
  {
    id: 3,
    gymId: "3333",
    firstName: "Daniel",
    lastName: "Cormier",
    rank: "brown",
  },
  {
    id: 4,
    gymId: "4444",
    firstName: "Demian",
    lastName: "Maia",
    rank: "black",
  },
  {
    id: 5,
    gymId: "5555",
    firstName: "Jan",
    lastName: "Blachowicz",
    rank: "purple",
  },
  {
    id: 6,
    gymId: "6666",
    firstName: "Anderson",
    lastName: "Silva",
    rank: "black",
  },
  {
    id: 7,
    gymId: "7777",
    firstName: "Jon",
    lastName: "Jones",
    rank: "white",
  },
  {
    id: 8,
    gymId: "8888",
    firstName: "Alistair",
    lastName: "Overeem",
    rank: "blue",
  },
  {
    id: 9,
    gymId: "9999",
    firstName: "Frank",
    lastName: "Mir",
    rank: "black",
  },
];
