export const SESSIONS = [
  {
    id: 0,
    sessionId: "0",
    date: "20210401T07:00:00",
    type: "Kickboxing",
    image: "../Shared/kickboxing.jpg",
    instructor: "Coach Jeff",
    capacity: 12,
  },
  {
    id: 1,
    sessionId: "1",
    date: "20210401T12:15:00",
    type: "Nogi Jiu Jitsu",
    image: "../Shared/nogijiujitsu.jpg",
    instructor: "Coach Zach",
    capacity: 12,
  },
  {
    id: 2,
    sessionId: "2",
    date: "20210401T19:00:00",
    type: "Brazilian Jiu Jitsu",
    image: "../Shared/gijiujitsu.jpg",
    instructor: "Coach Omar",
    capacity: 10,
  },
  {
    id: 3,
    sessionId: "3",
    date: "20210402T07:00:00",
    type: "Kickboxing",
    image: "../Shared/kickboxing.jpg",
    instructor: "Coach Jeff",
    capacity: 12,
  },
  {
    id: 4,
    sessionId: "4",
    date: "20210402T12:15:00",
    type: "Nogi Jiu Jitsu",
    image: "../Shared/nogijiujitsu.jpg",
    instructor: "Coach Zach",
    capacity: 12,
  },
  {
    id: 5,
    sessionId: "5",
    date: "20210402T19:00:00",
    type: "Brazilian Jiu Jitsu",
    image: "../Shared/gijiujitsu.jpg",
    instructor: "Coach Omar",
    capacity: 10,
  },
  {
    id: 6,
    sessionId: "6",
    date: "20210403T07:00:00",
    type: "Kickboxing",
    image: "../Shared/kickboxing.jpg",
    instructor: "Coach Jeff",
    capacity: 12,
  },
  {
    id: 7,
    sessionId: "7",
    date: "20210403T12:15:00",
    type: "Nogi Jiu Jitsu",
    image: "../Shared/nogijiujitsu.jpg",
    instructor: "Coach Zach",
    capacity: 12,
  },
  {
    id: 8,
    sessionId: "8",
    date: "20210403T19:00:00",
    type: "Brazilian Jiu Jitsu",
    image: "../Shared/gijiujitsu.jpg",
    instructor: "Coach Omar",
    capacity: 10,
  },
];
